// Comprehensive list of common BJJ positions used for suggestions
export const COMMON_BJJ_POSITIONS: string[] = [
  'Standing',
  'Closed Guard',
  'Open Guard',
  'Half Guard',
  'Side Control (Top)',
  'Side Control (Bottom)',
  'Mount (Top)',
  'Mount (Bottom)',
  'Back Control',
  'Knee on Belly',
  'Turtle',
  'Butterfly Guard',
  'Spider Guard',
  'De La Riva Guard',
  'Reverse De La Riva Guard',
  'X-Guard',
  'Single Leg X',
  'Lasso Guard',
  'Worm Guard',
  'Rubber Guard',
  'Z-Guard',
  '50/50',
  'Deep Half Guard',
  'Lockdown',
  'North-South',
  'Scarf Hold',
  'Crucifix',
  'Truck',
  'Wrestling Stance',
  'Single Leg',
  'Double Leg',
  'Body Lock',
  'Front Headlock',
  'Leg Drag',
  'Headquarters',
  'Combat Base',
  'Quarter Guard',
  'Knee Shield',
  'Coyote Guard',
  'Seated Guard',
  'Collar Sleeve Guard',
];
